2024-03-20T18:30:54|ERROR|camera_app|tried to disconnect camera_x: Spinnaker: Camera is not started. [-1002]
2024-03-20T18:30:59|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\LAB\Scopefoundry_projects\Plant_Macroscope\plant_timelapse_dual_measure.py", line 205, in run
    self.img = c.camera.get_nparray()
  File "C:\Users\LAB\Scopefoundry_projects\Flir_ScopeFoundry\camera_device.py", line 68, in get_nparray
    return self.cam.get_array()
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\simple_pyspin\__init__.py", line 221, in get_array
    img = self.cam.GetNextImage(PySpin.EVENT_TIMEOUT_INFINITE if wait else PySpin.EVENT_TIMEOUT_NONE)
  File "C:\Users\LAB\anaconda3\envs\scopefoundry\lib\site-packages\PySpin\PySpin.py", line 34318, in GetNextImage
    return _PySpin._SWIG_CamPtr_GetNextImage(self, *args)
_PySpin.SpinnakerException: Spinnaker: Stream is not started [-1010]

